### ISSUE TITLE
Output new gape extraction data to same format as BSA

### ISSUE THREAD

**Issue by cmazzio** [hfgem/BlechGapes#11]
Using the new cluster analysis code gape pulls - individual gapes are checked for frequency and strength - save the results to the same file format as BSA analyses do. Currently the BSA data used is stored in the hdf5 file under hf5.root.emg_BSA_results.gapes[:]

**Comment by hfgem** [comment]
Completed in linked development branch 11-output-new-gape-extraction-data-to....
